begin;
create extension if not exists pgtap with schema extensions;
select plan(44);

select has_table('public','body_regions','body_regions exists');
select has_table('public','muscle_groups','muscle_groups exists');
select has_table('public','muscles','muscles exists');
select has_table('public','equipment','equipment exists');
select has_table('public','exercises','exercises exists');
select has_table('public','exercise_aliases','exercise_aliases exists');
select has_table('public','exercise_muscles','exercise_muscles exists');
select has_table('public','exercise_equipment','exercise_equipment exists');
select has_table('public','exercise_instruction_steps','instructions exists');
select has_table('public','exercise_relations','relations exists');
select has_table('public','exercise_media','media exists');
select has_table('public','exercise_external_mappings','external mappings exists');

select is((select count(*) from public.exercises),37::bigint,'seed has 37 exercises');
select is((select count(*) from public.body_regions),3::bigint,'anatomy has body regions');
select is((select count(*) from public.muscle_groups),10::bigint,'anatomy covers ten requested groups');
select cmp_ok((select count(*) from public.muscles),'>=',24::bigint,'anatomy has useful muscle granularity');
select is((select count(*) from public.equipment),14::bigint,'equipment vocabulary is complete');
select is((select count(*) from public.exercises e where not exists(select 1 from public.exercise_muscles em where em.exercise_id=e.id and em.role='primary')),0::bigint,'every exercise has a primary muscle');
select is((select count(*) from public.exercises e where not exists(select 1 from public.exercise_equipment ee where ee.exercise_id=e.id)),0::bigint,'every seeded exercise has equipment');
select is((select count(*) from public.exercises where btrim(name_pt)='' or btrim(name_en)=''),0::bigint,'every exercise has PT and EN names');
select ok((select count(*)=count(distinct slug) from public.exercises),'exercise slugs are unique');
select is((select count(*) from public.exercises e where (select count(distinct language) from public.exercise_aliases a where a.exercise_id=e.id)<2),0::bigint,'every exercise has coherent PT and EN aliases');
select is((select count(*) from public.exercise_relations where source_exercise_id=target_exercise_id),0::bigint,'relations cannot point to self');
select is((select count(*) from public.exercise_relations r left join public.exercises s on s.id=r.source_exercise_id left join public.exercises t on t.id=r.target_exercise_id where s.id is null or t.id is null),0::bigint,'relations never dangle');
select is((select count(*) from public.exercises where movement_pattern not in ('horizontal_push','horizontal_pull','vertical_push','vertical_pull','squat','hinge','lunge','knee_flexion','knee_extension','elbow_flexion','elbow_extension','shoulder_abduction','shoulder_flexion','calf_raise','hip_abduction','hip_adduction','trunk_flexion','trunk_extension','anti_extension','anti_rotation','carry','other')),0::bigint,'movement vocabulary is intact');
select is((select count(*) from public.exercises where mechanics not in ('compound','isolation')),0::bigint,'mechanics vocabulary is intact');
select is((select count(*) from public.exercises where laterality not in ('bilateral','unilateral','alternating')),0::bigint,'laterality vocabulary is intact');
select is((select count(*) from public.exercise_muscles where role not in ('primary','secondary','stabilizer')),0::bigint,'muscle-role vocabulary is intact');
select is((select count(*) from public.exercises e where (select count(distinct section) from public.exercise_instruction_steps i where i.exercise_id=e.id)<5),0::bigint,'every exercise has all instruction sections');
select ok(exists(select 1 from information_schema.columns where table_schema='public' and table_name='exercise_media' and column_name='source_type'),'media records provenance type');
select ok(exists(select 1 from pg_constraint where conrelid='public.exercise_media'::regclass and conname='exercise_media_location_check'),'media provenance requires a coherent location');
select ok(exists(select 1 from pg_constraint where conrelid='public.exercise_external_mappings'::regclass and conname='exercise_external_mappings_provider_key'),'provider mappings cannot redefine identity');
select is((select count(*) from pg_class where relnamespace='public'::regnamespace and relname in ('body_regions','muscle_groups','muscles','equipment','exercises','exercise_aliases','exercise_muscles','exercise_equipment','exercise_instruction_steps','exercise_relations','exercise_media','exercise_external_mappings') and relrowsecurity),12::bigint,'RLS is enabled on every catalog table');
select ok(not has_table_privilege('anon','public.exercises','select') and not has_table_privilege('anon','public.muscles','select'),'anon has no catalog read grants');
select ok(has_table_privilege('authenticated','public.exercises','select') and has_table_privilege('authenticated','public.muscles','select') and has_table_privilege('authenticated','public.exercise_media','select'),'authenticated can read the catalog');
select ok(not has_table_privilege('authenticated','public.exercises','insert') and not has_table_privilege('authenticated','public.exercises','update') and not has_table_privilege('authenticated','public.exercises','delete'),'authenticated cannot mutate canonical exercises');
select throws_ok('set local role anon; select * from public.exercises','42501',null,'anon cannot read exercises at runtime');
reset role;
set local role authenticated;
select is((select count(*) from public.exercises),37::bigint,'authenticated reads all active catalog rows');
select throws_ok($$insert into public.exercises(id,slug,name_pt,name_en,short_description_pt,movement_pattern,mechanics,laterality) values(gen_random_uuid(),'client-write','x','x','x','other','isolation','bilateral')$$,'42501',null,'client cannot insert canonical exercises');
select is((select count(*) from public.search_exercise_catalog('flexao',null,null,null,null)),1::bigint,'search is case- and accent-insensitive');
select cmp_ok((select count(*) from public.search_exercise_catalog(null,null,null,'dumbbell',null)),'>=',8::bigint,'equipment filter returns matching exercises');
reset role;
select is((select count(*) from public.exercise_relations r where r.relation_type in ('similar_pattern','similar_target','equipment_alternative') and not exists(select 1 from public.exercise_relations reverse where reverse.source_exercise_id=r.target_exercise_id and reverse.target_exercise_id=r.source_exercise_id and reverse.relation_type=r.relation_type)),0::bigint,'symmetric relation types are stored both ways');
select is((select count(*) from information_schema.columns where table_schema='public' and table_name in ('body_regions','muscle_groups','muscles','equipment','exercises','exercise_aliases','exercise_muscles','exercise_equipment','exercise_instruction_steps','exercise_relations','exercise_media','exercise_external_mappings') and column_name='athlete_id'),0::bigint,'global catalog has no athlete_id');
select is((select id from public.exercises where slug='barbell-bench-press'),'50000000-0000-4000-8000-000000000001'::uuid,'canonical exercise identity is stable');

select * from finish();
rollback;
